version: '3.9'

services:
  # web:
  #   build:
  #     dockerfile: docker/Dockerfile
  #     context: .
  #   ports:
  #     - "8100:8100"
  #   restart: on-failure
  #   env_file:
  #     - ./conf/.env
  #   depends_on:
  #     web_db:
  #       condition: service_healthy

  announce_db:
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_db
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "main_db" ]
      interval: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: